### ISSUE TITLE
OpenFOAM 5 fails to register pointDisplacement

### ISSUE THREAD

**Issue by DavidSCN** [precice/openfoam-adapter#123]
Using the FSI module of the adapter with OpenFOAM 5 leads to the following error message:
```cpp
--> FOAM Warning : 
    From function void adapterInfo(std::__cxx11::string, std::__cxx11::string)
    in file Utilities.C at line 50
    Error (deferred - will exit later) in the preCICE adapter: 

    request for pointVectorField pointDisplacement from objectRegistry region0 failed
    available objects of type pointVectorField are
0()

```
The error can easily be reproduced by trying to run one of the FSI tutorials. In this case, the OF-deal.II tutorials have been used. 

The error does not occur for the same setup and OpenFOAM 6. I have not checked it for other OpenFOAM versions.

**Comment by MakisH** [comment]
This is a known issue originating from the merging of OpenFOAM solvers at OpenFOAM 6 and ?v1712?. We are getting the solver from the `controlDict`, where we need to define pimpleDyMFoam for older versions and pimpleFoam for newer versions.

Since we (should) support the latest OpenFOAM versions by default, and since we don't have any solver versions in the tutorials repository, we have set it to "pimpleFoam" by default. Running `Allrun` or `runFluid` shows a hint at the end.

Unless you have any better idea on how to approach this, I would just close it.

**Comment by DavidSCN** [comment]
Ok I see. Maybe we should remove the `removeObsoleteFolders.sh` message or formulate the main oint there shorter to motivate people to read it. 
Is there an option to get the version information and abort the simulation using the shell scripts before the simulation starts? I guess this would be another option. Anyway, I'm fine with closing it, if it is known.

**Comment by MakisH** [comment]
If we could find a nice way to do it, of course, let's just do it. But then the issue is different ("guess the correct OpenFOAM solver") and should go into the tutorials.

But, be prepared, OpenFOAM does not have a consistent way to get the version. At least not a way that goes back until OpenFOAM 5. See also #32

**Comment by DavidSCN** [comment]
Alright, for now I will close it
