### ISSUE TITLE
endTime for CHT case

### ISSUE THREAD

**Issue by jaydeshpande** [precice/openfoam-adapter#14]
[https://1drv.ms/u/s!AvEMDnpUbHI2ggCtaUp6pvMLnj5O](url)

Here's a test case. I made the endtime to 4s. The simulation still stops after 1s. I must have made some mistake somewhere that it doesn't capture the end time correctly.

**Comment by jaydeshpande** [comment]
Oh wait, I think I figured out. It needs to be updated in precice-config.xml. Now it does work. I thought, preCICE will look for endTime from controlDict.

**Comment by MakisH** [comment]
Hey,

yes, we need to ignore the endTime set in OpenFOAM, in order to solve both technical and design problems. 

Since an endTime appears in every participant, as well as in preCICE, we need to decide on which value to use. We get the one from preCICE.

Moreover, setting the endTime in OpenFOAM to be exactly as much as needed would cause problems in the implicit coupling, where a checkpoint may need to be read again before exiting. OpenFOAM calls the `execute()` method of the function objects only once during the (suposed to be) last timestep. Therefore, we set it to infinity and end the simulation manually when preCICE says so.
