### ISSUE TITLE
Undocumented dependency to pkg-config

### ISSUE THREAD

**Issue by muh-hassani** [precice/openfoam-adapter#205]
I followed the instruction how to build the adapter from [here](https://precice.org/adapter-openfoam-get.html), but the ./Allwmake fails with the following error:
```
Building the OpenFOAM-preCICE adapter...
./Allwmake: 35: pkg-config: not found
```
I have installed precice and openfoam2106 as debian packages.  Then I downloaded the adapter `openfoam-adapter_v1.0.0_OpenFOAMv1812-v2012` and ran simply the `./Allwmake` command. I did not change any thing in the `Allwmake` file, and ran it with the default configuration. Please let me know if any other information is required.

**Comment by DavidSCN** [comment]
Which OS are you using? If you don't have pkg-config installed, you could simply install it using `apt-get install -y pkg-config` or similar (depending on your OS).

**Comment by muh-hassani** [comment]
> apt-get install -y pkg-config

thanks @DavidSCN, it worked. Sorry I was not aware that `pkg-config` is actually a package itself! I installed it on my WSL which runs an ubuntu variant.

**Comment by MakisH** [comment]
I am reopening this since it is actually a good point: we assume pkg-config, without documenting it anywhere.

This is not a package requirement of the preCICE Debian package, either, as it is only needed by some adapters.

We can at least add a [troubleshooting item](https://precice.org/adapter-openfoam-get.html#troubleshooting), and potentially add some general note in the "get the adapter" and "quickstart" pages.

pkg-config is a very common dependency, but if a user installs Linux specifically for preCICE, then this is something they may run into.
