### ISSUE TITLE
Early OpenFOAM versions don't support certain string types from C++11

### ISSUE THREAD

**Issue by huangq1234553** [precice/openfoam-adapter#83]
Compiled OpenFOAM 4.0 with Boost 1.69 / yaml  0.6.0.

Determined that early/certain versions of OpenFOAM enforce the -std=c++0x flag in wmake rules. This will cause certain string types introduced in C++11 to not be supported or have undefined symbols after the adapter compiles.

wmake rules are found in
$PATH_TO_OPENFOAM/wmake/rules/linux64Gcc (for example)

This is likely why certain combinations of OpenFOAM versions / libraries will result in undefined symbols in the ldd.log.

Possible to change the rules files to use -std=c++11, which allows working compilation, but side-effects on OpenFOAM have not been investigated.

**Comment by MakisH** [comment]
So, if I understand correctly, this affects only Boost 1.69 and newer.

On my machine I have Boost 1.67 and OpenFOAM precompiled. My `$WM_CXXFLAGS` is `-std=c++0x`, but my `$WM_PROJECT_DIR/wmake/rules/linux64Gcc/c++` specifies `-std=c++11`.

Does this mean that OpenFOAM needs to be recompiled, or just that the adapter (which uses yaml-cpp) needs to be recompiled? I have forgotten how these OpenFOAM rules work...

**Comment by MakisH** [comment]
This issue is quite vague, but it still may explain the incompatibilities with yaml-cpp.

Looking at yaml-cpp 0.6.3, I see that C++11 is required by CMake:
https://github.com/jbeder/yaml-cpp/blob/yaml-cpp-0.6.3/CMakeLists.txt#L268-L271

Looking also at yaml-cpp 0.5.3, I see that [no standard is defined](https://github.com/jbeder/yaml-cpp/blob/release-0.5.2/CMakeLists.txt). I cannot reproduce the problem, but this could be the reason. More precisely, I suspect that [this commit](https://github.com/jbeder/yaml-cpp/commit/24fa1b33805c9a91df0f32c46c28e314dd7ad96f) introduced the breaking changes.

The problem should not really be Boost, but that we are enforcing C++11, but the older yaml-cpp not. Similarly, that Boost enforces C++11 (or newer), but older the yaml-cpp not.

I think that what @huangq1234553 means with this issue is presented in a nutshell in [this StackOverflow answer](https://stackoverflow.com/a/34571794/2254346):

> The old `std::string` was not compliant with C++11 because that standard prohibits a copy-on-write implementation. There was no way to create a compliant std::string without breaking ABI, so they did so with a way to return to the non-compliant version for ABI compatibility.

Therefore, my suggestion (which I now added into our wiki) is to always build yaml-cpp with the C++11 specifications, with "build the latest yaml-cpp from source" being the easiest advice.

In any case, this is not something we can "fix" just in the adapter, even though we can give clearer instructions in the documentation on how to build yaml-cpp. I consider this issue closed.
